// <auto-generated />

namespace Purview.EventSourcing.Aggregates;

/// <summary>
/// Marks a property on a generated aggregate as participating in
/// aggregate validation/transformation configuration.
/// </summary>
{{CodeGen}}
[global::System.AttributeUsage(global::System.AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
sealed class AggregateValidationAttribute : global::System.Attribute
{
}
