// <auto-generated />

#nullable enable

namespace Purview.EventSourcing.Aggregates;

/// <summary>
/// Marks an event parameter as a deterministic computed value.
/// The parameter can be omitted by callers via an optional default
/// and is finalized by the generated <c>OnComputing{EventName}</c> hook
/// before the event is recorded.
/// </summary>
{{CodeGen}}
[global::System.AttributeUsage(global::System.AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
sealed class ComputedAttribute : global::System.Attribute;
