// <auto-generated />

namespace Purview.EventSourcing.Aggregates;

/// <summary>
/// Marks a method on a <see cref="GenerateAggregateAttribute"/>-decorated class
/// as a command that should have an event class and registration generated.
/// <para>
/// The method parameters become the event's properties. The generator creates:
/// <list type="bullet">
///   <item>An event class named <c>{MethodName}Event</c> extending <c>EventBase</c></item>
///   <item>A <c>Register&lt;{MethodName}Event&gt;(Apply)</c> call in <c>RegisterEvents()</c></item>
///   <item>An <c>Apply({MethodName}Event)</c> method that sets matching properties</item>
///   <item>The method body calls <c>RecordAndApply(new {MethodName}Event { ... })</c></item>
/// </list>
/// </para>
/// </summary>
/// <remarks>
/// Use <see cref="Version"/> to declare the schema version of the generated event class.
/// Increment this value whenever the event's properties change in a breaking way.
/// The generated event class will override <c>SchemaVersion</c> to return this value.
/// </remarks>
[global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
[global::System.Diagnostics.Conditional("PURVIEW_EVENTSOURCING_ATTRIBUTES")]
sealed class GenerateAggregateEventAttribute : global::System.Attribute
{
	/// <summary>
	/// The schema version of the generated event class. Defaults to 1.
	/// Increment when the event's properties change in a breaking way.
	/// </summary>
	public int Version { get; set; } = 1;
}
