// <auto-generated />

namespace Purview.EventSourcing.Aggregates;

/// <summary>
/// Marks a partial class extending <c>AggregateBase</c> for source generation.
/// The generator will create the <c>RegisterEvents()</c> override and
/// event classes based on methods decorated with <see cref="GenerateAggregateEventAttribute"/>.
/// </summary>
[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
[global::System.Diagnostics.Conditional("PURVIEW_EVENTSOURCING_ATTRIBUTES")]
sealed class GenerateAggregateAttribute : global::System.Attribute
{
}
