using System.Text;
using Microsoft.CodeAnalysis;

namespace Purview.EventSourcing.SourceGenerator.Helpers;

static class EmitHelper
{
	public static string GenerateAggregateSource(AggregateInfo info)
	{
		var sb = new StringBuilder();

		sb.AppendLine("// <auto-generated />");
		sb.AppendLine("#nullable enable");
		sb.AppendLine();

		// Generate event classes in a nested Events namespace
		if (info.Methods.Count > 0)
		{
			var eventsNamespace = info.Namespace is not null
				? $"{info.Namespace}.Events"
				: "Events";

			sb.AppendLine($"namespace {eventsNamespace}");
			sb.AppendLine("{");

			foreach (var method in info.Methods)
			{
				GenerateEventClass(sb, method);
			}

			sb.AppendLine("}");
			sb.AppendLine();
		}

		// Generate the partial aggregate class in a block-scoped namespace
		// (required because event classes use a different namespace in the same file)
		var accessModifier = GetAccessModifier(info.Accessibility);

		if (info.Namespace is not null)
		{
			sb.AppendLine($"namespace {info.Namespace}");
			sb.AppendLine("{");
		}

		var indent = info.Namespace is not null ? "\t" : "";

		sb.AppendLine($"{indent}{accessModifier} partial class {info.ClassName}");
		sb.AppendLine($"{indent}{{");

		// Generate RegisterEvents override
		GenerateRegisterEvents(sb, info, indent);

		// Generate Apply methods
		foreach (var method in info.Methods)
		{
			GenerateApplyMethod(sb, info, method, indent);
		}

		// Generate command method implementations
		foreach (var method in info.Methods)
		{
			GenerateCommandMethod(sb, info, method, indent);
		}

		sb.AppendLine($"{indent}}}");

		if (info.Namespace is not null)
		{
			sb.AppendLine("}");
		}

		return sb.ToString();
	}

	static void GenerateEventClass(StringBuilder sb, AggregateEventMethodInfo method)
	{
		sb.AppendLine($"\tpublic sealed class {method.EventName} : global::Purview.EventSourcing.Aggregates.Events.EventBase");
		sb.AppendLine("\t{");

		foreach (var prop in method.Parameters)
		{
			sb.AppendLine($"\t\tpublic {prop.TypeName} {prop.PropertyName} {{ get; set; }} = default!;");
		}

		sb.AppendLine();
		sb.AppendLine("\t\tprotected override void BuildEventHash(ref global::System.HashCode hash)");
		sb.AppendLine("\t\t{");

		foreach (var prop in method.Parameters)
		{
			sb.AppendLine($"\t\t\thash.Add({prop.PropertyName});");
		}

		sb.AppendLine("\t\t}");
		sb.AppendLine("\t}");
		sb.AppendLine();
	}

	static void GenerateRegisterEvents(StringBuilder sb, AggregateInfo info, string indent)
	{
		sb.AppendLine($"{indent}\tprotected override void RegisterEvents()");
		sb.AppendLine($"{indent}\t{{");

		var eventsNamespace = info.Namespace is not null
			? $"{info.Namespace}.Events"
			: "Events";

		foreach (var method in info.Methods)
		{
			sb.AppendLine($"{indent}\t\tRegister<global::{eventsNamespace}.{method.EventName}>(Apply);");
		}

		sb.AppendLine($"{indent}\t}}");
		sb.AppendLine();
	}

	static void GenerateApplyMethod(StringBuilder sb, AggregateInfo info, AggregateEventMethodInfo method, string indent)
	{
		var eventsNamespace = info.Namespace is not null
			? $"{info.Namespace}.Events"
			: "Events";

		sb.AppendLine($"{indent}\tvoid Apply(global::{eventsNamespace}.{method.EventName} @event)");
		sb.AppendLine($"{indent}\t{{");

		foreach (var prop in method.Parameters)
		{
			sb.AppendLine($"{indent}\t\t{prop.PropertyName} = @event.{prop.PropertyName};");
		}

		sb.AppendLine($"{indent}\t}}");
		sb.AppendLine();
	}

	static void GenerateCommandMethod(StringBuilder sb, AggregateInfo info, AggregateEventMethodInfo method, string indent)
	{
		var eventsNamespace = info.Namespace is not null
			? $"{info.Namespace}.Events"
			: "Events";

		// Build parameter list
		var paramList = new StringBuilder();
		for (var i = 0; i < method.Parameters.Count; i++)
		{
			if (i > 0)
				paramList.Append(", ");
			paramList.Append($"{method.Parameters[i].TypeName} {method.Parameters[i].ParameterName}");
		}

		sb.AppendLine($"{indent}\tpublic partial void {method.MethodName}({paramList})");
		sb.AppendLine($"{indent}\t{{");

		// Build event initialization
		sb.Append($"{indent}\t\tRecordAndApply(new global::{eventsNamespace}.{method.EventName}");

		if (method.Parameters.Count > 0)
		{
			sb.AppendLine();
			sb.AppendLine($"{indent}\t\t{{");
			foreach (var prop in method.Parameters)
			{
				sb.AppendLine($"{indent}\t\t\t{prop.PropertyName} = {prop.ParameterName},");
			}

			sb.Append($"{indent}\t\t}}");
		}
		else
		{
			sb.Append("()");
		}

		sb.AppendLine(");");
		sb.AppendLine($"{indent}\t}}");
		sb.AppendLine();
	}

	static string GetAccessModifier(Accessibility accessibility)
	{
		switch (accessibility)
		{
			case Accessibility.Public:
				return "public";
			case Accessibility.Internal:
				return "internal";
			case Accessibility.Protected:
				return "protected";
			case Accessibility.ProtectedOrInternal:
				return "protected internal";
			case Accessibility.ProtectedAndInternal:
				return "private protected";
			default:
				return "internal";
		}
	}
}
