using System.Text;
using Microsoft.CodeAnalysis;

namespace Purview.EventSourcing.SourceGenerator.Helpers;

static class EmitHelper
{
	public static string GenerateAggregateSource(AggregateInfo info, GenerationLogger? logger)
	{
		logger?.Debug(
			$"Generating source for aggregate '{info.ClassName}' with {info.Methods.Count} event methods and {info.InvalidMethods.Count} invalid methods."
		);

		StringBuilder sb = new();

		sb.AppendLine("// <auto-generated />");
		sb.AppendLine("#nullable enable");
		sb.AppendLine();

		// Generate event classes in a nested Events namespace
		if (info.Methods.Count > 0)
		{
			foreach (
				var namespaceMethods in info.Methods.GroupBy(
					static method => method.EventNamespace,
					StringComparer.Ordinal
				)
			)
			{
				sb.AppendLine($"namespace {namespaceMethods.Key}");
				sb.AppendLine("{");

				foreach (var method in namespaceMethods)
				{
					GenerateEventClass(sb, method, logger);
				}

				sb.AppendLine("}");
				sb.AppendLine();
			}
		}

		// Generate the partial aggregate class in a block-scoped namespace
		// (required because event classes use a different namespace in the same file)
		var accessModifier = GetAccessModifier(info.Accessibility);

		if (info.Namespace is not null)
		{
			sb.AppendLine($"namespace {info.Namespace}");
			sb.AppendLine("{");
		}

		var indent = info.Namespace is not null ? "\t" : "";

		sb.AppendLine(
			$"{indent}[global::System.Text.Json.Serialization.JsonConverter(typeof({info.ClassName}JsonConverter))]"
		);
		sb.AppendLine($"{indent}{accessModifier} partial class {info.ClassName}");
		sb.AppendLine($"{indent}{{");

		GenerateJsonSerializationSupport(sb, info, indent);

		// Generate RegisterEvents override
		GenerateRegisterEvents(sb, info, indent);

		// Generate Apply methods
		foreach (var method in info.Methods)
		{
			GenerateApplyMethod(sb, info, method, indent);
		}

		// Generate command method implementations
		foreach (var method in info.Methods)
		{
			GenerateCommandMethod(sb, info, method, indent);
		}

		GeneratePropertyHookDeclarations(sb, info, indent);

		foreach (var method in info.InvalidMethods)
		{
			GenerateInvalidCommandMethodStub(sb, method, indent);
		}

		sb.AppendLine($"{indent}}}");

		GenerateJsonConverter(sb, info, indent);
		GenerateJsonModel(sb, info, indent);

		if (info.Namespace is not null)
		{
			sb.AppendLine("}");
		}

		return sb.ToString();
	}

	static void GenerateEventClass(StringBuilder sb, AggregateEventMethodInfo method, GenerationLogger? logger)
	{
		logger?.Debug(
			$"Generating event class '{method.EventName}' for method '{method.MethodName}' with {method.Parameters.Count} parameters and version {method.Version}."
		);

		var hashParameterName = method.Parameters.Count == 0 ? "_" : "hash";

		sb.AppendLine(
			$"\tpublic sealed class {method.EventName} : global::Purview.EventSourcing.Aggregates.Events.EventBase"
		);
		sb.AppendLine("\t{");

		foreach (var prop in method.Parameters)
		{
			sb.AppendLine($"\t\tpublic {prop.PropertyTypeName} {prop.PropertyName} {{ get; set; }} = default!;");
		}

		sb.AppendLine();

		// Emit SchemaVersion override only when it differs from the default (1),
		// but always emit it so consumers can rely on it being present.
		sb.AppendLine($"\t\tpublic override int SchemaVersion => {method.Version};");
		sb.AppendLine();

		sb.AppendLine($"\t\tprotected override void BuildEventHash(ref global::System.HashCode {hashParameterName})");
		sb.AppendLine("\t\t{");

		foreach (var prop in method.Parameters)
		{
			sb.AppendLine($"\t\t\t{hashParameterName}.Add({prop.PropertyName});");
		}

		sb.AppendLine("\t\t}");
		sb.AppendLine("\t}");
		sb.AppendLine();
	}

	static void GenerateRegisterEvents(StringBuilder sb, AggregateInfo info, string indent)
	{
		sb.AppendLine($"{indent}\tprotected override void RegisterEvents()");
		sb.AppendLine($"{indent}\t{{");

		foreach (var method in info.Methods)
		{
			sb.AppendLine($"{indent}\t\tRegister<global::{method.EventNamespace}.{method.EventName}>(Apply);");
		}

		sb.AppendLine($"{indent}\t}}");
		sb.AppendLine();
	}

	static void GenerateJsonSerializationSupport(StringBuilder sb, AggregateInfo info, string indent)
	{
		sb.AppendLine(
			$"{indent}\tinternal static {info.ClassName} CreateFromJsonModel({info.ClassName}JsonModel jsonModel) => new()"
		);
		sb.AppendLine($"{indent}\t\t{{");
		sb.AppendLine(
			$"{indent}\t\t\tDetails = jsonModel.Details ?? new global::Purview.EventSourcing.Aggregates.AggregateDetails(),"
		);

		foreach (var property in info.Properties)
		{
			sb.AppendLine($"{indent}\t\t\t{property.PropertyName} = jsonModel.{property.PropertyName},");
		}

		sb.AppendLine($"{indent}\t\t}};");
		sb.AppendLine();

		sb.AppendLine($"{indent}\tinternal {info.ClassName}JsonModel ToJsonModel() => new()");
		sb.AppendLine($"{indent}\t\t{{");
		sb.AppendLine($"{indent}\t\t\tDetails = Details,");

		foreach (var property in info.Properties)
		{
			sb.AppendLine($"{indent}\t\t\t{property.PropertyName} = {property.PropertyName},");
		}

		sb.AppendLine($"{indent}\t\t}};");
		sb.AppendLine();
	}

	static void GenerateApplyMethod(StringBuilder sb, AggregateInfo _, AggregateEventMethodInfo method, string indent)
	{
		var eventParameterName = method.Parameters.Count == 0 ? "_" : "@event";
		var mappedParameters = method.Parameters.Where(static parameter => parameter.HasAggregateProperty).ToList();

		sb.AppendLine($"{indent}\tvoid Apply(global::{method.EventNamespace}.{method.EventName} {eventParameterName})");
		sb.AppendLine($"{indent}\t{{");

		foreach (var prop in mappedParameters)
		{
			sb.AppendLine($"{indent}\t\tvar __previous{prop.AggregatePropertyName} = {prop.AggregatePropertyName};");
		}

		if (mappedParameters.Count > 0)
			sb.AppendLine();

		foreach (var prop in mappedParameters)
		{
			sb.AppendLine($"{indent}\t\t{prop.AggregatePropertyName} = {eventParameterName}.{prop.PropertyName};");
		}

		if (mappedParameters.Count > 0)
			sb.AppendLine();

		foreach (var prop in mappedParameters)
		{
			sb.AppendLine(
				$"{indent}\t\tOn{prop.AggregatePropertyName}Changed(__previous{prop.AggregatePropertyName}, {prop.AggregatePropertyName});"
			);
		}

		var hookSuffix = GetHookSuffix(method.EventName);
		sb.AppendLine($"{indent}\t\tOnApplied{hookSuffix}({eventParameterName});");
		sb.AppendLine($"{indent}\t}}");
		sb.AppendLine();
	}

	static void GenerateCommandMethod(StringBuilder sb, AggregateInfo info, AggregateEventMethodInfo method, string indent)
	{
		var paramList = new StringBuilder();
		for (var i = 0; i < method.Parameters.Count; i++)
		{
			if (i > 0)
				paramList.Append(", ");
			paramList.Append($"{method.Parameters[i].ParameterTypeName} {method.Parameters[i].ParameterName}");
		}

		var hookSuffix = GetHookSuffix(method.EventName);
		var methodAccessModifier = GetAccessModifier(method.MethodAccessibility);
		sb.AppendLine(
			$"{indent}\t{methodAccessModifier} partial {method.ReturnTypeName} {method.MethodName}({paramList})"
		);
		sb.AppendLine($"{indent}\t{{");

		if (method.Parameters.Count > 0)
		{
			var mappedParameters = method.Parameters.Where(static parameter => parameter.HasAggregateProperty).ToList();

			foreach (var prop in method.Parameters)
			{
				if (prop.ParameterConversionKind is EventParameterConversionKind.None)
					continue;

				sb.AppendLine(
					$"{indent}\t\tvar {GetLocalValueName(prop)} = {BuildPropertyValueExpression(info, method, prop)};"
				);
			}

			if (method.Parameters.Any(static p => p.ParameterConversionKind is not EventParameterConversionKind.None))
				sb.AppendLine();

			if (mappedParameters.Count > 0)
			{
				sb.AppendLine($"{indent}\t\tif ({BuildUnchangedCondition(mappedParameters)})");
				sb.AppendLine($"{indent}\t\t{{");
				EmitNoChangeReturn(sb, method.ReturnKind, indent, 3);
				sb.AppendLine($"{indent}\t\t}}");
				sb.AppendLine();
			}

			foreach (var prop in mappedParameters)
			{
				sb.AppendLine($"{indent}\t\tOn{prop.AggregatePropertyName}Changing(ref {GetWorkingValueName(prop)});");
			}

			if (mappedParameters.Count > 0)
				sb.AppendLine();
		}

		if (method.Parameters.Count == 0)
			sb.AppendLine($"{indent}\t\tOnCreating{hookSuffix}();");
		else
		{
			sb.AppendLine(
				$"{indent}\t\tOnCreating{hookSuffix}({BuildOnCreatingCallArgumentList(method.Parameters)});"
			);
		}

		sb.AppendLine();
		sb.AppendLine($"{indent}\t\tvar @event = new global::{method.EventNamespace}.{method.EventName}");

		if (method.Parameters.Count > 0)
		{
			sb.AppendLine($"{indent}\t\t{{");
			foreach (var prop in method.Parameters)
			{
				sb.AppendLine($"{indent}\t\t\t{prop.PropertyName} = {GetWorkingValueName(prop)},");
			}

			sb.AppendLine($"{indent}\t\t}};");
		}
		else
		{
			sb.AppendLine($"{indent}\t\t();");
		}

		sb.AppendLine();
		sb.AppendLine($"{indent}\t\tOnCreated{hookSuffix}(@event);");
		sb.AppendLine($"{indent}\t\tRecordAndApply(@event);");
		sb.AppendLine();
		EmitSuccessReturn(sb, method.ReturnKind, indent, 2);

		sb.AppendLine($"{indent}\t}}");
		sb.AppendLine();

		EmitCa1822Suppression(sb, indent);
		if (method.Parameters.Count == 0)
			sb.AppendLine($"{indent}\tpartial void OnCreating{hookSuffix}();");
		else
		{
			sb.AppendLine(
				$"{indent}\tpartial void OnCreating{hookSuffix}({BuildOnCreatingDeclarationParameterList(method.Parameters)});"
			);
		}

		EmitCa1822Suppression(sb, indent);
		sb.AppendLine(
			$"{indent}\tpartial void OnCreated{hookSuffix}(global::{method.EventNamespace}.{method.EventName} @event);"
		);
		EmitCa1822Suppression(sb, indent);
		sb.AppendLine(
			$"{indent}\tpartial void OnApplied{hookSuffix}(global::{method.EventNamespace}.{method.EventName} @event);"
		);
		sb.AppendLine();
	}

	static void GeneratePropertyHookDeclarations(StringBuilder sb, AggregateInfo info, string indent)
	{
		var aggregateProperties = info
			.Methods.SelectMany(static method => method.Parameters)
			.Where(static parameter => parameter.HasAggregateProperty)
			.GroupBy(static parameter => parameter.AggregatePropertyName, StringComparer.Ordinal)
			.Select(static group => group.First())
			.ToList();

		foreach (var prop in aggregateProperties)
		{
			EmitCa1822Suppression(sb, indent);
			sb.AppendLine(
				$"{indent}\tpartial void On{prop.AggregatePropertyName}Changing(ref {prop.PropertyTypeName} {prop.ParameterName});"
			);
			EmitCa1822Suppression(sb, indent);
			sb.AppendLine(
				$"{indent}\tpartial void On{prop.AggregatePropertyName}Changed({prop.PropertyTypeName} previous, {prop.PropertyTypeName} current);"
			);
			sb.AppendLine();
		}
	}

	static void EmitCa1822Suppression(StringBuilder sb, string indent) =>
		sb.AppendLine(
			$"{indent}\t[global::System.Diagnostics.CodeAnalysis.SuppressMessage(\"Performance\", \"CA1822:Mark members as static\", Justification = \"Generated partial hook declaration must match instance signature and cannot be static.\")]"
		);

	static string GetHookSuffix(string eventName) =>
		eventName.EndsWith("Event", global::System.StringComparison.Ordinal)
			? eventName.Substring(0, eventName.Length - 5)
			: eventName;

	static string GetLocalValueName(EventPropertyInfo parameter) => $"__{parameter.ParameterName}Value";

	static string BuildOnCreatingCallArgumentList(List<EventPropertyInfo> parameters) =>
		string.Join(", ", parameters.Select(static parameter => $"ref {GetWorkingValueName(parameter)}"));

	static string BuildOnCreatingDeclarationParameterList(List<EventPropertyInfo> parameters) =>
		string.Join(
			", ",
			parameters.Select(static parameter => $"ref {parameter.PropertyTypeName} {parameter.ParameterName}")
		);

	static string BuildPropertyValueExpression(
		AggregateInfo info,
		AggregateEventMethodInfo method,
		EventPropertyInfo parameter
	)
	{
		var aggregateTypeName = GetAggregateTypeName(info);

		return parameter.ParameterConversionKind switch
		{
			EventParameterConversionKind.None => parameter.ParameterName,
			EventParameterConversionKind.Implicit =>
				$"({parameter.PropertyTypeName}){parameter.ParameterName}",
			EventParameterConversionKind.Create =>
				$"{parameter.PropertyTypeName}.Create({parameter.ParameterName})",
			EventParameterConversionKind.ContextualCreate =>
				$"{parameter.PropertyTypeName}.Create({parameter.ParameterName}, new global::Purview.EventSourcing.ValueObjects.ValueObjectContext<{aggregateTypeName}>(this, MemberName: nameof({parameter.AggregatePropertyName}), EventName: nameof(global::{method.EventNamespace}.{method.EventName})))",
			_ => parameter.ParameterName,
		};
	}

	static string GetAggregateTypeName(AggregateInfo info) =>
		info.Namespace is null ? $"global::{info.ClassName}" : $"global::{info.Namespace}.{info.ClassName}";

	static string BuildUnchangedCondition(List<EventPropertyInfo> parameters)
	{
		return string.Join(" && ", parameters.Select(BuildUnchangedComparison));
	}

	static string BuildUnchangedComparison(EventPropertyInfo parameter)
	{
		var comparisonValue = GetWorkingValueName(parameter);

		return parameter.UseStringOrdinalComparison
			? $"global::System.String.Equals({parameter.AggregatePropertyName}, {comparisonValue}, global::System.StringComparison.Ordinal)"
			: $"global::System.Collections.Generic.EqualityComparer<{parameter.EqualityComparerTypeName}>.Default.Equals({parameter.AggregatePropertyName}, {comparisonValue})";
	}

	static string GetWorkingValueName(EventPropertyInfo parameter) =>
		parameter.ParameterConversionKind is EventParameterConversionKind.None
			? parameter.ParameterName
			: GetLocalValueName(parameter);

	static void EmitNoChangeReturn(StringBuilder sb, EventMethodReturnKind returnKind, string indent, int indentDepth)
	{
		var methodIndent = indent + new string('\t', indentDepth);
		switch (returnKind)
		{
			case EventMethodReturnKind.Void:
				sb.AppendLine($"{methodIndent}return;");
				break;
			case EventMethodReturnKind.Aggregate:
				sb.AppendLine($"{methodIndent}return this;");
				break;
			case EventMethodReturnKind.Bool:
				sb.AppendLine($"{methodIndent}return false;");
				break;
			default:
				sb.AppendLine($"{methodIndent}return;");
				break;
		}
	}

	static void EmitSuccessReturn(StringBuilder sb, EventMethodReturnKind returnKind, string indent, int indentDepth)
	{
		var methodIndent = indent + new string('\t', indentDepth);
		switch (returnKind)
		{
			case EventMethodReturnKind.Void:
				sb.AppendLine($"{methodIndent}return;");
				break;
			case EventMethodReturnKind.Aggregate:
				sb.AppendLine($"{methodIndent}return this;");
				break;
			case EventMethodReturnKind.Bool:
				sb.AppendLine($"{methodIndent}return true;");
				break;
			default:
				sb.AppendLine($"{methodIndent}return;");
				break;
		}
	}

	static void GenerateInvalidCommandMethodStub(
		StringBuilder sb,
		InvalidAggregateEventMethodInfo method,
		string indent
	)
	{
		var diagnosticIds =
			method.DiagnosticIds.Length > 0 ? string.Join(", ", method.DiagnosticIds) : "unknown diagnostic IDs";
		var message = EscapeStringLiteral(
			$"The generated aggregate event method '{method.Signature}' is unavailable because [GenerateAggregateEvent] validation failed. Review the suppressed generator diagnostics for this method ({diagnosticIds})."
		);

		sb.AppendLine($"{indent}\t{method.Signature}");
		sb.AppendLine($"{indent}\t{{");
		sb.AppendLine($"{indent}\t\tthrow new global::System.InvalidOperationException(\"{message}\");");
		sb.AppendLine($"{indent}\t}}");
		sb.AppendLine();
	}

	static string EscapeStringLiteral(string value) =>
		value
			.Replace("\\", "\\\\")
			.Replace("\"", "\\\"")
			.Replace("\r", "\\r")
			.Replace("\n", "\\n")
			.Replace("\t", "\\t");

	static string GetAccessModifier(Accessibility accessibility)
	{
		return accessibility switch
		{
			Accessibility.Public => "public",
			Accessibility.Private => "private",
			Accessibility.Internal => "internal",
			Accessibility.Protected => "protected",
			Accessibility.ProtectedOrInternal => "protected internal",
			Accessibility.ProtectedAndInternal => "private protected",
			_ => "internal",
		};
	}

	static void GenerateJsonConverter(StringBuilder sb, AggregateInfo info, string indent)
	{
		sb.AppendLine();
		sb.AppendLine(
			$"{indent}sealed class {info.ClassName}JsonConverter : global::System.Text.Json.Serialization.JsonConverter<{info.ClassName}>"
		);
		sb.AppendLine($"{indent}{{");
		sb.AppendLine(
			$"{indent}\tpublic override {info.ClassName}? Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)"
		);
		sb.AppendLine($"{indent}\t{{");
		sb.AppendLine(
			$"{indent}\t\tvar jsonModel = global::System.Text.Json.JsonSerializer.Deserialize<{info.ClassName}JsonModel>(ref reader, options);"
		);
		sb.AppendLine($"{indent}\t\tif (jsonModel is null)");
		sb.AppendLine(
			$"{indent}\t\t\tthrow new global::System.Text.Json.JsonException(\"Unable to deserialize {info.ClassName}.\");"
		);
		sb.AppendLine();
		sb.AppendLine($"{indent}\t\treturn {info.ClassName}.CreateFromJsonModel(jsonModel);");
		sb.AppendLine($"{indent}\t}}");
		sb.AppendLine();
		sb.AppendLine(
			$"{indent}\tpublic override void Write(global::System.Text.Json.Utf8JsonWriter writer, {info.ClassName} value, global::System.Text.Json.JsonSerializerOptions options)"
		);
		sb.AppendLine($"{indent}\t{{");
		sb.AppendLine(
			$"{indent}\t\tglobal::System.Text.Json.JsonSerializer.Serialize(writer, value.ToJsonModel(), options);"
		);
		sb.AppendLine($"{indent}\t}}");
		sb.AppendLine($"{indent}}}");
	}

	static void GenerateJsonModel(StringBuilder sb, AggregateInfo info, string indent)
	{
		sb.AppendLine();
		sb.AppendLine($"{indent}sealed class {info.ClassName}JsonModel");
		sb.AppendLine($"{indent}{{");
		sb.AppendLine(
			$"{indent}\tpublic global::Purview.EventSourcing.Aggregates.AggregateDetails? Details {{ get; set; }} = new();"
		);

		foreach (var property in info.Properties)
		{
			sb.AppendLine($"{indent}\tpublic {property.TypeName} {property.PropertyName} {{ get; set; }} = default!;");
		}

		sb.AppendLine($"{indent}}}");
	}
}
